# Generated by Django 4.1.1 on 2022-09-16 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jenismobil',
            fields=[
                ('idjenismobil', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('namamobil', models.CharField(max_length=8)),
                ('jumlahmobil', models.IntegerField()),
                ('hargasewa', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='karyawan',
            fields=[
                ('idkaryawan', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=10)),
                ('alamat', models.CharField(max_length=20)),
                ('nomortelepon', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='mobil',
            fields=[
                ('idmobil', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nopolisi', models.CharField(max_length=8)),
                ('konfirmasi', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='penyewa',
            fields=[
                ('idpenyewa', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=10)),
                ('nomortelepon', models.IntegerField()),
                ('alamat', models.CharField(max_length=20)),
                ('nomorktp', models.IntegerField()),
                ('dokumen', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='penyewaan',
            fields=[
                ('idpenyewaan', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tanggalpenyewaan', models.DateField()),
                ('durasi', models.IntegerField()),
                ('tanggalpengembalian', models.DateField()),
                ('idkaryawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.karyawan')),
                ('idmobil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mobil')),
                ('idpenyewa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.penyewa')),
            ],
        ),
    ]
