# Generated by Django 4.1.1 on 2022-09-18 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobil',
            name='idjenismobil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.jenismobil'),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='konfirmasi',
            field=models.BooleanField(),
        ),
    ]
