# Generated by Django 4.1.1 on 2022-10-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mobil_idjenismobil_alter_mobil_konfirmasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jenismobil',
            name='idjenismobil',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jenismobil',
            name='namamobil',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='karyawan',
            name='alamat',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='karyawan',
            name='idkaryawan',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mobil',
            name='idmobil',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='penyewa',
            name='alamat',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='penyewa',
            name='idpenyewa',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='penyewa',
            name='nama',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='penyewaan',
            name='idpenyewaan',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
